### ISSUE TITLE
[SR - task] Todo 생성

### ISSUE THREAD

**Issue by Joo614** [Joo614/Practice-Todo-Application#2]
### 만들고자 하는 기능
- Todo 생성 기능

### 해당 기능을 구현하기 위해 할 일
1. [ ] Entity 클래스 생성
2. [ ] Controller 클래스 생성
3. [ ] Service 클래스 생성
4. [ ] Dto 클래스 생성

### 예상 작업 시간
- 30분
