### ISSUE TITLE
[Bare - task] Todo 삭제

### ISSUE THREAD

**Issue by Joo614** [Joo614/Practice-Todo-Application#5]
### 만들고자 하는 기능
- Todo 삭제 기능

### 해당 기능을 구현하기 위해 할 일
1. [ ] Entity 클래스 생성
2. [ ] Controller 클래스 생성
3. [ ] Service 클래스 생성
4. [ ] Dto 클래스 생성
5. [ ]  Mapper 인터페이스 생성
6. [ ] Repository 인터페이스 생성

### 예상 작업 시간
- 30분
